name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy worker
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Deploy worker
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "apps/worker"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: bun
